name: cherry_consume
description: "체리컨슘 앱. 작업 005"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  file_picker: ^13.1.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  google_sign_in: ^7.2.0
  http: ^1.6.0
  kakao_flutter_sdk_user: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
